### ISSUE TITLE
Adopt aggregated apiserver

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb-operator#1002]
## Feature Request

**Is your feature request related to a problem? Please describe:**
According to #986 #981 #936 , there are more and more features requires a feasible way to validate, defaults, converse and intercept custom resources.

CRD has been adopted in tidb-operator to define custom resources, but the resources defined by CRD are eventually processed by kube-apiserver. So custom logics upon the CRUD time of resources can only be implemented via hooks (typically webhook), which are tedious to setup and bounded by the extension point provided by kube-apiserver. For example, resource conversion hook is only available in k8s 1.15 or higher.

**Describe the feature you'd like:**
I propose to adopt aggregated apiserver to host custom resources that requires custom logic that hard to implement for CRD.

## Progress

- [x] Skeleton and toolchain #1048 
- [x] ~SharedInformer based watch~ Tracked separately in #1059 
- [x] Installation within tidb-operator #1060 
- [x] Unit tests #1048 
- [x] E2E tests #1058 
- [x] Tests in managed kubernetes
  - [x] ACK (Aliyun)
  - [x] AWS
  - [x] GKE
- [x] ~Detailed Usage example and recipe~ Tracked separately in https://github.com/pingcap/tidb-operator/issues/1143

**Comment by aylei** [comment]
Closing according to the todo list
