### ISSUE TITLE
Migrating Helm chart template logic to server side

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#1121]
## Feature Request

Currently, many resources are created and managed solely by the Helm chart. Embedding logic in the chart template makes it hard to add some features, such as the unit computation and conversion between PD/TiKV's and K8s's. It also makes it difficult to write automatic tests, validation logic and backward compatible code. Besides, users have to use both kubectl and helm to manage tidb clusters, this adds extra complexity.

Now we have introduced [aggregated apiserver](https://github.com/pingcap/tidb-operator/issues/1002). We should migrate Helm chart template logic to the controller-manager or aggregated apiserver.

Below are lists of resources we should migrate to server-side:

- [x] tidb-discovery service  #1322 
- [ ] tidb-initializer job #1262
- [x] tidb service #1190 #1242
- [x] tidb configmaps and start-script #1192 
- [x] pd configmaps and start-script #1263 https://github.com/pingcap/tidb-operator/pull/1330
- [x] tikv configmaps and start-script #1264 https://github.com/pingcap/tidb-operator/pull/1330
- [x] pump #1191 
- [ ] monitor #1261

ref: server dry-run https://github.com/pingcap/tidb-operator/issues/999

**Comment by gregwebs** [comment]
This makes it harder for users to hack changes (Now they have to compile tidb-operator) or to even understand ahead of time what would happen. I am wondering if we can have a dry run feature to emit all the resources that tidb-operator would create. I guess this is similar to another feature request to have a plan feature like terraform, but that may be more focused on update?

**Comment by tennix** [comment]
Since we will have the aggregated apiserver, before the CRs are written into k8s, we can emit a plan (server-side dry run). I guess this can solve your worries.
But yes, to change the spec or resources we don't expose requires changing Go code can re-compile tidb-operator. We lose some flexibility but gain more correctness. Just as dynamic programming languages vs. static programming languages.

**Comment by gregwebs** [comment]
yes, server side dry-run (create and update) would help.

**Comment by aylei** [comment]
@tennix @gregwebs I reference the dry-run issue in the description, however, one thing worries me is that the PD/TiKV/TiDB are still created with ordered dependencies in our controller. I remember that you have a proposal to create them simultaneously, how is it going then? @gregwebs

**Comment by gregwebs** [comment]
> how is it going then? @gregwebs
We just need to finalize testing on the PR now.

**Comment by cofyc** [comment]
should we remove dependencies on these annotations keys:

https://github.com/pingcap/tidb-operator/blob/b91846337e454258f0d1c75ad2caceee33ea63de/charts/tidb-cluster/templates/tidb-cluster.yaml#L12-L15

lots of code use these keys.

**Comment by aylei** [comment]
Yes, we should, the controller should not rely on certain labels

**Comment by aylei** [comment]
tracked in https://github.com/pingcap/tidb-operator/issues/1418

**Comment by aylei** [comment]
closed
