### ISSUE TITLE
exposing the tidb cluster states/changes as k8s events to users

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#1375]
Many users report that they cannot know what the `tidb-operator` is doing when `failover` occurs, which confuses them.

We need to expose the internal state of the cluster to users with the help of `Events` or `ContainerConditions`, or anything else, for example:

```
$ kubectl describe tc <tc-name>
...
Events:
  Type     Reason            Age                 From            Message
  ----     ------            ----                ----            -------
  Warning  StoreOffline  26s (x25 over 45s)  tidb-controler  store-1 is offline 2 minitues
  Warning  StoreDown     17s (x25 over 41s)  tidb-controler  store-1 is down 30 minutes
  Warning  Failover      17s (x25 over 41s)  tidb-controler  store-1 failover occurs now
  ...
```
* [x] tidb scheduler (Done) https://github.com/pingcap/tidb-operator/pull/1373
* [x] pd failover (WIP) #1465  https://github.com/pingcap/tidb-operator/pull/1466
* [ ] tikv failover
* [ ] tidb failover
* [ ] emit an event when pd member status changed https://github.com/pingcap/tidb-operator/issues/1495
* [ ] setting the events BurstSize/QPS to proper values https://github.com/pingcap/tidb-operator/issues/1494
* [ ] Emit an event when a failed(Failover) member recovers https://github.com/pingcap/tidb-operator/issues/1798
