### ISSUE TITLE
Integrate with TiDB v4.0

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#1666]
This issue is to trace the overall progress of integration with TiDB v4.0:

- [x] Configuration parameters update integration https://github.com/pingcap/tidb-operator/issues/1661
- [x] Dynamic config update integration https://github.com/pingcap/tidb-operator/issues/1662
- [x] TiDB Dashboard integration https://github.com/pingcap/tidb-operator/issues/1663
- [x] TiDB Server command-line option update https://github.com/pingcap/tidb-operator/issues/1439
- [x] Add e2e and stability test cases https://github.com/pingcap/tidb-operator/issues/1665
