### ISSUE TITLE
Support heterogeneous design

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb-operator#2240]
## Description

Currently, the spec for the `TidbCluster` describes a group of `PD`/`TiKV`/`TiDB` instances. 
For each component, the spec is the same for all of the Pods. 
This design is easy to use and also covers the most cases for using the TiDB cluster.

However, as a distributed database with clear and multiple layers, we may need to deploy the component with different configurations to meet the different requirements.

For example, as the SQL layer, the TiDB component could be composed of multiple instances with different resource requests and configurations to handle the different workloads (AP/TP query). 
For the storage layer, the TiKV component could be composed of multiple instances with different store labels which determine the data distribution among different instances. 
And this is also useful for the auto-scaling case, where we may want to scale out TiDBs/TiKVs with different resources or configurations from the original TidbCluster.

To implement the above proposal, we can:

- Make the `spec.pd`, `spec.tidb`, and `spec.tikv` optional in the TidbCluster CR, e.g. change them to pointer. 
- Add cluster reference in the TidbCluster CR so that the components can start with the pdAddress in the cluster reference. 

In this case, we can:

- Deploy TidbCluster CR with `spec.tikv` + `spec.pdAddress` to deploy a TiKV cluster with different configurations and join the existing TiDB Cluster
- Deploy TidbCluster CR with `spec.tidb` + `spec.pdAddress` to deploy a TiDB cluster with different configurations and join the existing TiDB Cluster
- Actually all of the supported components in the TidbCluster CR, e.g. TiFlash can be deployed with different configurations with minor changes.

## Category

Feature

## Value

Support heterogeneous structured components of TiDB Cluster on Kubernetes

## TODO lists

* P0 features

  * [x] Make the `spec.pd`, `spec.tidb`, and `spec.tikv` optional in the TidbCluster CR, e.g. change them to pointer. #2971
  * [x] Add TidbCluster Reference in the TidbCluster CR #2972 
  * [x] TidbCluster controller update for the `spec.pd`, `spec.tidb`, and `spec.tikv` change. #2973 
  * [x] TidbCluster controller update for the change in #2972, so that the components can start with the pdAddress in the cluster reference. (Focus on TiKV and TiDB first) #2974 

* P1 features

  * [x] The status of each TidbCluster should only include the components managed by this TidbCluster and based on this, the failureMembers/failureStores will only include the Pods managed by this TidbCluster so that failover function can work normally #2975
  * [x] TidbCluster controller update for the change in #2972, so that the components can start with the pdAddress in the cluster reference. (Focus on TiFlash) #3038 
  * [x] TLS support for heterogeneous components #3061
  * [x] Monitoring for heterogeneous components #3062
  * [x] Doc update https://github.com/pingcap/docs-tidb-operator/issues/707

## Workload Estimation (P0 features)
30

## Time

DevProgress: 100% 
QAProgress: 100% 
DocProgress: 100% 

GanttStart: 2020-07-20
GanttDue: 2020-09-30

**Comment by DanielZhangQD** [comment]
We decide to reuse the existing `TudbCluster` CR to implement the heterogeneous deployment.
Record the original solution here:

## Description

Currently, the spec for the `TidbCluster` describes a group of `PD`/`TiKV`/`TiDB` instances. For each kind of components, 
their specs are all the same. This design is easy to use and also covers the most cases for using the tidb cluster.

However, as a distributed database with clear and multilayers, the components in each layer could be different from 
each other to meet the different requirements.

For example, as the SQL layer, tidb components could be composed of multiple instances with different resource requests 
and configurations to handle the different workloads (AP/TP query). For the storage layer, tikv components could be 
composed of multiple instances with different store labels which decided the data distribution as a whole storage system.

Add 2 new CRD as `TiKVGroup` and `TiDBGroup` which represents a group of TiDB and TiKV instances. As a whole system, one
TiDB Cluster can be composed of one `TidbCluster` and multiple `TiKVGroup` and `TiDBGroup`. Here is the basic example:

For `TiKVGroup`:

```golang
type TiKVGroup struct {
	Spec   TiKVGroupSpec
	Status TiKVGroupStatus
}

type TiKVGroupSpec struct {
    TiKVSpec
    ClusterName string
}

type TiKVGroupStatus struct {
    TiKVStatus
}
```


## Category

Cloud TiDB

## Value

Support heterogeneous structured TidbCluster on Kubernetes

## TODO lists

* P0 features (support TiKVGroup Controller)

  * [x] Support TiKVGroup/TiDBGroup API design
  * [x] Support Controller For TiKVGroup
  * [ ] Support Upgrading For TiKVGroup
  * [ ] Support Scaling For TiKVGroup

* P1 features (support TiDBGroup Controller / TiKVGroup Failover)

  * [ ] Support Controller For TiDBGroup
  * [ ] Support Upgrading For TiDBGroup
  * [ ] Support Scaling For TiDBGroup
  * [ ] Support Failover for TiDBGroup Pods
  * [ ] Support Failover for TiKVGroup Pods
  * [ ] Support setting Timezone for TiKVGroup & TiDBGroup Pods

* P3 features
  * [ ] Support Mixed Structured Design for TiKVGroup / TiDBGroup

## Documentions 

[document](https://github.com/pingcap/tidb-operator/blob/master/docs/design-proposals/2020-06-12-heterogeneous-design-for-tidb-cluister.md)

**Comment by DanielZhangQD** [comment]
@mikechengwei You can take this issue if it's OK.
Thanks for your contribution!

**Comment by DanielZhangQD** [comment]
@cofyc Please also help review the solution here https://github.com/pingcap/tidb-operator/issues/2240#issue-603688992

**Comment by cofyc** [comment]
can you make an update to the proposal here ?
https://github.com/pingcap/tidb-operator/blob/master/docs/design-proposals/2020-06-12-heterogeneous-design-for-tidb-cluister.md

**Comment by DanielZhangQD** [comment]
OK.

**Comment by cofyc** [comment]
SGTM

**Comment by uglyengineer** [comment]
This issue is a sub-item of https://github.com/pingcap/tidb/issues/18374, no need to be directly related in Longterm board.

**Comment by DanielZhangQD** [comment]
@mikechengwei Thanks a lot for your contribution!
