### ISSUE TITLE
Improve the robustness and stability of TiDB-Operator

### ISSUE THREAD

**Issue by lonng** [pingcap/tidb-operator#2821]
## Description

Improve TiDB-Operator test coverage (both unit test and e2e test)

https://codecov.io/gh/pingcap/tidb-operator/tree/master/

## TODO

- [x] improve `pkg/backup` https://github.com/pingcap/tidb-operator/issues/2920 @july2993 
- [ ] improve `cmd/backup-manager/app` https://github.com/pingcap/tidb-operator/issues/3469
- [x] improve UT for `pkg/controller` https://github.com/pingcap/tidb-operator/pull/3465 @AstroProfundis
- [x] improve UT for TiFlash https://github.com/pingcap/tidb-operator/issues/2927
- [x] improve UT for webhook https://github.com/pingcap/tidb-operator/issues/2938 @july2993 
- [x] improve UT for util https://github.com/pingcap/tidb-operator/issues/2940 @july2993 
- [x] Improve UT coverage for pkg/manager/member/tidb_init_manager.go https://github.com/pingcap/tidb-operator/issues/3032 @AstroProfundis
- [x] improve UT for TiCDC https://github.com/pingcap/tidb-operator/issues/3024 @AstroProfundis 
- [x] improve UT for pkg/manager/meta https://github.com/pingcap/tidb-operator/issues/3030
- [x] improve UT for pdapi https://github.com/pingcap/tidb-operator/issues/2939
- [x] improve UT for upgrade/featurs pkgs https://github.com/pingcap/tidb-operator/pull/2965
- [x] improve UT for discovery https://github.com/pingcap/tidb-operator/pull/2991
- [x] improve UT for webhook/statefulset pkg https://github.com/pingcap/tidb-operator/pull/2997
- [x] improve UT for pod_restarter and pvc_cleaner https://github.com/pingcap/tidb-operator/pull/3095

## Goal 

Total test coverage reaches 60% at the end of Q3.

## Workload Estimation
60, still need 50 person-day in 7-28

## Time

GanttProgress: 93%
GanttStart: 2020-08-01
GanttDue: 2020-11-30

**Comment by DanielZhangQD** [comment]
Is it necessary to add a TODO item to count the coverage result of E2E test?

**Comment by cofyc** [comment]
> Is it necessary to add a TODO item to count the coverage result of E2E test?

added

**Comment by july2993** [comment]
`pkg/manager/meta` already 69.4%, should be ok for now?

**Comment by AstroProfundis** [comment]
![图片](https://user-images.githubusercontent.com/596538/98920710-625c0d80-250b-11eb-81c6-a3b3ee532311.png)
