### ISSUE TITLE
Refactor Tidbmonitor design.

### ISSUE THREAD

**Issue by mikechengwei** [pingcap/tidb-operator#3292]
## Description

Currently, there are some problems with TiDBMonitor. We organize the requirements and list the requirements that need improvement.

1. TiDBMonitor is a stateful application but is created as a deployment. We should switch to StatefulSet. #2968
2. TiDBMonitor monitors multiple TiDB clusters for both TLS and non-TLS environment.
    After discussion, we will not support monitoring multiple clusters with one TidbMonitor when TLS enabled because this would require the following restrictions:
* All of the monitored clusters have to enable TLS
* Users must ensure that all the monitored clusters use the same CA certificate
* A dedicated cluster client secret needs to be created for TidbMonitor

The above restrictions are not reasonable so we will just support monitoring multiple clusters with TLS disabled with one TidbMonitor.
3. Monitor multiple TiDB Clusters with users own Prometheus #3184
    We can provide an example with Prometheus Operator.
4. Aggregate the monitoring data of multiple TiDB Clusters, we can refer to the Prometheus operator and support the Thanos spec.  #3118 #3117
5. Combination of Kubernetes monitoring and TiDB cluster monitoring. #3099
6. add external fields for `kubectl get tm` command. #2169 #2982
7. Grafana dashboards for multiple clusters.
8. The PD Dashboard monitor address is currently TidbCluster controller updated, it should be updated by tidbmonitor controller. And PD dashboard doesn't support multiple clusters.
9. Prometheus need to reload configuration  when spec filed cause configMap update .

   -  We can regenerate configMap name cause deployment rolling update.
   - Hot update configuration through reloader and call prometheus reload api (More user-friendly).

## Category
Feature

## Value
Refactor tidbMonitor.

## TODO lists
- P0 features
	- [x] Tidbmonitor monitors multiple clusters across multiple ns in tls and non-tls envrionments. #3307 
	- [x] Support generating the Grafana dashboard of multiple clusters.
- P1 features	
	- [x] Smooth upgrade deployment to StatefulSet. #2968
	- [x] Support Thanos spec and optimize Thanos example. #3553
	- [ ] Optimize TiDB service, more friendly support with Prometheus operator `ServiceMonitor`.
	- [x] Refactor for PD dashboard address writing.  #3924
	- [x] TidbMonitor multiple replica. #2968 #3815 sloved.

- P2 feature
	- [ ] Fix the combination of Kubernetes monitoring and TiDB cluster monitoring.
	- [x] Add more external fields for `kubectl get tm` command. #3958

Extra features:

- [x] support monitor multiple dm across multiple ns in tls and non-tls environments.
- [x] No need to replace the cluster name in https://github.com/pingcap/monitoring/blob/master/platform-monitoring/operator/init.sh
- [x] The tc parameters in the various functions in pkg/monitor/monitor/monitor_manager.go and pkg/monitor/monitor/util.go can be removed.
- [ ] Optimize `createorupdateSecret` method,reduce interaction with apiserver.
## Workload Estimation (P0 features)
30

## Time
GanttStart: 2020-10-01
GanttDue: 2020-12-31

## Project

**Comment by DanielZhangQD** [comment]
@mikechengwei Thanks for summarizing this!
For item 7 as below, please hold on for the update, we need to evaluate it further.
```
The PD Dashboard monitor address is currently TidbCluster controller updated, it should be updated by tidbmonitor controller. And PD dashboard doesn't support multiple clusters.
```

**Comment by howardlau1999** [comment]
Currently, if the TiDBMonitor spec is updated, although the ConfigMap for scrape_config is updated, the Prometheus does not reload the newer config. Could you also add an item for Prometheus config reloader as the prometheus-operator do?

**Comment by mikechengwei** [comment]
9. Prometheus need to reload configuration when spec filed cause configMap update .

- We can regenerate configMap name cause deployment rolling update.
- Hot update configuration through reloader and call prometheus reload api.  @howardlau1999

**Comment by DanielZhangQD** [comment]
Support monitoring heterogeneous clusters, which is also used by the auto-scaling feature.

**Comment by mikechengwei** [comment]
I think we don‘t need to optimize tidb service and adapt to prometheus operator, because we use custom monitor by TiDBMonitor.

**Comment by DanielZhangQD** [comment]
> I think we don‘t need to optimize tidb service and adapt to prometheus operator, because we use custom monitor by TiDBMonitor.

@mikechengwei We can just provide some examples for the users that use Prometheus operator to deploy and manage their own Prometheus, do you think the example [here](https://github.com/pingcap/tidb-operator/blob/master/examples/prometheus-operator/README.md) needs any improvement?

**Comment by DanielZhangQD** [comment]
The following items to be done after #3867:
1. DM
2. No need to replace the cluster name in https://github.com/pingcap/monitoring/blob/master/platform-monitoring/operator/init.sh
3. The `tc` parameters in the various functions in `pkg/monitor/monitor/monitor_manager.go` and `pkg/monitor/monitor/util.go` can be removed.

**Comment by mikechengwei** [comment]
Optimize `createorupdateSecret` method.
