### ISSUE TITLE
Release v1.1.10

### ISSUE THREAD

**Issue by BinChenn** [pingcap/tidb-operator#3754]
This is an issue tracking the tidb-operator v1.1.10 release.

Previous:
- #2567
- #2775
- #2839
- #3010
- #3140
- #3263
- #3380
- #3495
- #3616 
- #3656 

Pending PRs:

TODO:
- [x] Update release notes [#1090](https://github.com/pingcap/docs-tidb-operator/pull/1090)
- [x] Update default version of TiDB Operator (#3756 )
- [x] Update TiDB version and tools version if necessary (#3757)
- [x] Update TiDB Operator version in docs-tidb-operator repo [#1088](https://github.com/pingcap/docs-tidb-operator/pull/1088)
- [x] Update TiDB version in the docs-tidb-operator repo if necessary [#1087](https://github.com/pingcap/docs-tidb-operator/pull/1087)
- [x] Build and publish docker images/helm charts
- [x] Update Github Releases
- [x] Announcement (slack, email, etc.)
