### ISSUE TITLE
Optimize heterogeneous across Kubernetes

### ISSUE THREAD

**Issue by KanShiori** [pingcap/tidb-operator#4390]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

- [x] fix the issue that heterogeneous TiFlash use unreachable addr about TiDB #4406 
- [x] optmize e2e case #4397
- [x] use `spec.acrossK8s` to decide if tc is heterogeneou across Kubernetes #4400
- [x] ensure `clusterDomain` just be used to generate addr #4408
- [x] remove cert in discovery when local pd isn' exist #4405

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**
