### ISSUE TITLE
Automatic failover feature proposal

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#47]
@tennix @onlymellb @xiaojingchen and @weekface discussed the automatic failover for PD, TiKV, and TiDB yesterday, this is a talk summary.

## Failure definition
When a node of k8s node can't work or other reasons, the tidb component (PD/TiKV/TiDB) can't work properly (Obtained by query the pd API), the TiDB Operator needs to be able to observe this situation and take active intervention and increase the replicas, these scenarios include:

1. pd member is not healthy for a while, can be obtained from PD Cluster's `/pd/health` API
2. tikv state is not Up for a while, can be obtained from PD Cluster's `/pd/api/v1/stores` API
3. tidb can't respond for a while, can be obtained from tidb instance's `/status` API

## PD automatic failover
When a PD peer was  observed as the failure for a while  (add a `LastTransitionTime` attr to PDStatus) ~(can implement as a Informer like k8s)~, operator should:
1. mark this peer as the failure
2. invoke `deleteMember` api to delete this member from the pd cluster
3. increase the replicas to add a new PD peer
4. try to delete the PVC and Pod of this PD peer over and over, let StatefulSet create the new PD peer with the same ordinal, but not use the tombstone PV
5. decrease the replicas when all members are ready again

## TiKV automatic failover
When a TiKV peer was observed as failure for a while  (add a `LastTransitionTime` attr to TiKVStatus) ~(can implement as a Informer like k8s also)~, for example: its state is not `Up`, operator just increase the replicas to add a new TiKV peer, that is all.

## TiDB automatic failover
When a TiDB peer was observed as the failure for a while (add a `LastTransitionTime` attr to TiDBStatus) ~(can implement as a Informer like k8s also)~, operator should:
1. increase the replicas to add a new TiDB peer
2. decrease the replicas when all members are ready again

This feature will be split into multiple PRs and any suggestions will be welcomed.

- [ ] ~add [Informer](https://github.com/pingcap/tidb-operator/tree/master/pkg/client/informers/externalversions) function to pdControl~
- [x] PD automatic failover, issue #57 PR #74 
- [x] TiKV automatic failover, issue #58 PR #77 
- [x] TiDB automatic failover, issue #59 PR #86

**Comment by gregwebs** [comment]
For TiDB it mentions decreasing the replicas when a node comes back. What about TiKV?

**Comment by tennix** [comment]
@gregwebs Decreasing the replicas for StatefulSet means removing pods by descending order. For TiDB it is OK since it's almost stateless (TiDB will register itself in PD in the future, but it doesn't have persistent data itself). But for TiKV, removing pods means migrating data, it may have a big influence on the user's business, also removing in this order may be not preferred. So we should let users manually decide when and which TiKV to delete.

**Comment by gregwebs** [comment]
It seems like this is a problem with using StatefulSet? If we were not constrained by ordinal we might consider deleting the original pod if a new one was already running with migrated data.

**Comment by gregwebs** [comment]
I am excited to see this take shape and this is a great high-level overview. It does leave me with questions about the details. I think it will be very helpful to go from this high-level overview to a more detailed specification that lists out details of the failure scenarios and operator/tidb responses.

**Comment by weekface** [comment]
@gregwebs I had updated the description. Add the details failure scenarios and other minor fixes.
