### ISSUE TITLE
graceful upgrade feature proposal

### ISSUE THREAD

**Issue by xiaojingchen** [pingcap/tidb-operator#92]
### why need the graceful upgrade
The current upgrade feature is a simple rolling upgrade which is provided by `StatefulSet`, the upgrading way has the following problems:
- During the upgrade process, the database business will be affected. For example, if a tikv pod is the leader of multiple data regions, its upgrade will cause this part of the data to be temporarily unavailable until the cluster re-elects the leaders.
- The current upgrade cannot ensure high availability. Although the statefulSet guarantees that the pod is upgraded one by one, its upgrade operate based on the state of a pod, but the pod state is running does not mean that tikv or pd is already available. Therefore, there may be multiple instances is unavailable in the upgrade process. 
### How to implements graceful upgrade
1. The `StatefulSet` upgrade strategy use `RollingUpdateStatefulSetStrategy` and set `Partition` to control the upgrade
2. Use the status provided by pd instead of the pod status to determine if it can be upgraded.
3. Call pd's api to complete the leader's transfer or other operations before upgrade.

This feature will be split into multiple PRs in which more details will be added:
- [x]  PD graceful upgrade #94 
- [x] TiKV graceful upgrade #93 
- [x] TiDB graceful upgrade #89

**Comment by gregwebs** [comment]
Should this be closed now?
