### ISSUE TITLE
tkctl: production environment preflight check

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb-operator#936]
## Feature Request

Adding preflight check subcommand for `tkctl`.

To help get started with tidb in Kubernetes, we have not set any limitations of the deployment. But for production deployment, if some hardware/software requirements not satisfied or cluster not properly configured, there will be serious problems in production.

We can migrate [tidb-ansible](https://github.com/pingcap/tidb-ansible) preflight check of hardware and kernel parameter to `tkctl` subcommand. For cluster configuration check, we should check the `values.yaml` file of tidb cluster.

Below is the checklist:

- [x] Container cpu/memory requests/limits #900 
- [x] Cluster component version #900 
- [x] Component configuration validation #900 
- [x] Log level #900 
- [x] TiKV/Pump sync log #900 
- [x] TiKV block cache configurations #900 
- [x] Load balancer configuration #900 
- [x] TiDB binlog ignore-error option #900 
- [ ] Experimental features
- [ ] Storage class check: pv reclaim policy, local pv
- [ ] Kernel version and parameters
- [ ] K8s and Docker version
- [ ] Multiple TiDB Operator deployed?
- [ ] Monitoring and Logging deployed?
- [ ] CPU/Memory: cores, frequency, numa, swap
- [ ] Disk: performance, mount options, local volume provisioner setup, /etc/fstab
- [ ] Network: MTU, firewalld, selinux, ntp, dns, route, listening ports

**Comment by tennix** [comment]
As we've already aggregated apiserver, we should do the validation from server-side.

And for the k8s environment check, we can have some helper scripts to do this. It's more like a best practice.

So I will close this issue, and open other issues for tracking.
